#!/bin/sh

CONFIG_LOCATION="$XDG_CONFIG_HOME"/rdpmanager/config

[ ! -d "$XDG_CONFIG_HOME"/rdpmanager ] && mkdir "$XDG_CONFIG_HOME"/rdpmanager

[ ! -d "$XDG_CONFIG_HOME"/rdpmanager/rdp ] && mkdir "$XDG_CONFIG_HOME"/rdpmanager/rdp


if [ ! -f "$CONFIG_LOCATION" ]; then
	echo '#!/bin/bash
	# This is the base configuration file
	# Your Preferences are stored here
	
	 UI="Term"

	 PROG="xrdp"

	 BASEDIR="$XDG_CONFIG_HOME/rdpmanager/rdp"

	 BASEOPTIONS="+auto-reconnect +clipboard /cert:tofu"' > $XDG_CONFIG_HOME/rdpmanager/config
fi

. $CONFIG_LOCATION

CONNECTIONS=$(ls -1 $BASEDIR)

select OPT in CREATE UPDATE DELETE $CONNECTIONS QUIT; do
	case $OPT in
		CREATE)
			echo "Name of connection"
			read NAME
			echo "IP/hostname:"
			read IP
			echo "User:"
			read USER
			echo "Password:"
			read PASSWORD
			echo "Add a domain?(y/n):"
			read DOMAIN_CHECK
			if [ $DOMAIN_CHECK == "y" ]; then
				echo "Domain:"
				read DOMAIN
				echo 'xfreerdp3 /v:'$IP' /d':$DOMAIN '/u:'$USER' /p:'$PASSWORD $BASEOPTIONS> $BASEDIR/$NAME
			fi
			if [ $DOMAIN_CHECK == "n" ]; then
			echo 'xfreerdp3 /v:'$IP' /u:'$USER' /p:'$PASSWORD $BASEOPTIONS > $BASEDIR/$NAME
			fi
			chmod +x $BASEDIR/$NAME
			exit 1
			;;
		UPDATE)
			echo "not implemented"
			exit 1
			;;
		DELETE)
			select OPT2 in $CONNECTIONS; do
				rm -f $BASEDIR/$OPT2
				break
			done
			;;
		QUIT) 
			exit 0
			;;
		*) sh $BASEDIR/$OPT
			;;
	esac
	break
done
